language: cpp
dist: trusty
python:
    - 2.7
    - 3.4

notifications:
    email: false

before_install:
    # install pyenv
    - curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
    - pyenv update
    - sudo apt-get -qq update
    - sudo apt-get install -y python3 python3-dev python-dev
    - sudo pyenv global 3.5 

install:
    - mkdir build && cd build && cmake ..

script:
    - make -j8 all
    - make test
