language: cpp

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y python3 python3-dev

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make -j8 all
    - make test
