function(AddTest SrcName)
    add_executable(${SrcName} "${SrcName}.cpp")
    target_link_libraries(${SrcName} "gtest_main" ${ARGN})
    add_test(NAME "TEST_${SrcName}" COMMAND $<TARGET_FILE:${SrcName}>)
endfunction(AddTest)

function(AddLib SrcName)
    if ((${ARGC} GREATER 1) AND (NOT ${ARG1} EQUAL "STATIC"))
        add_library(${SrcName} SHARED "${SrcName}.cpp")
        target_link_libraries(${SrcName} ${ARGN})
    else()
        add_library(${SrcName} STATIC "${SrcName}.cpp")
        list(REMOVE_AT ARGN 0)
        target_link_libraries(${SrcName} ${ARGN})
    endif((${ARGC} GREATER 1) AND (NOT ${ARG1} EQUAL "STATIC"))
endfunction(AddLib)
